name: Release
on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.x

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Semantic Release
        run: >
          npx 
          -p semantic-release 
          -p @semantic-release/commit-analyzer
          -p @semantic-release/release-notes-generator
          -p @semantic-release/changelog 
          -p @semantic-release/git 
          -p @semantic-release/github 
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}